# Generated by Django 4.1.4 on 2023-07-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmiosfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-number'], 'verbose_name_plural': 'Student-List'},
        ),
    ]
